version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: ppdt_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppdt_db
      MYSQL_USER: ppdtuser
      MYSQL_PASSWORD: ppdtpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppdt_backend
    environment:
      DB_HOST: mysql
      DB_USER: ppdtuser
      DB_PASSWORD: ppdtpass
      DB_NAME: ppdt_db
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ppdt_frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mysql-data:
